<?php

namespace ProjetBundle\Repository;

/**
 * AgenceFinancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenceFinancementRepository extends \Doctrine\ORM\EntityRepository
{
}
