<?php

namespace ProjetBundle\Repository;

/**
 * BailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BailleurRepository extends \Doctrine\ORM\EntityRepository
{
}
