<?php

namespace ProjetBundle\Repository;

/**
 * ObjectifSpecifiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObjectifSpecifiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
