<?php

namespace ProjetBundle\Repository;

/**
 * ProjetAgenceFinancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetAgenceFinancementRepository extends \Doctrine\ORM\EntityRepository
{
}
