<?php

namespace ProjetBundle\Repository;

/**
 * ProjetBailleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetBailleurRepository extends \Doctrine\ORM\EntityRepository
{
}
