<?php

namespace ProjetBundle\Repository;

/**
 * ProjetInstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetInstitutionRepository extends \Doctrine\ORM\EntityRepository
{
}
